<a href="https://colab.research.google.com/github/MahmoudHamdySH/Assighnment-3/blob/main/Session_6_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt 
import numpy as np 

In [2]:
(train_X,train_y),(test_X,test_y)=mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
print(train_X.shape,test_X.shape)

(60000, 28, 28) (10000, 28, 28)


In [5]:
train_X=train_X/255
test_X=test_X/255

In [6]:
train_y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [10]:
from tensorflow.keras.utils import to_categorical
train_y=to_categorical(train_y)

In [11]:
train_y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [12]:
train_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Dropout

In [21]:
model=Sequential()
model.add(Flatten(input_shape=(28,28)))
model.add(Dense(32,activation = 'relu'))
model.add(Dense(64,activation = 'relu'))
model.add(Dropout(0.3))
model.add(Dense(10,activation = 'softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_5 (Dense)             (None, 32)                25120     
                                                                 
 dense_6 (Dense)             (None, 64)                2112      
                                                                 
 dropout (Dropout)           (None, 64)                0         
                                                                 
 dense_7 (Dense)             (None, 10)                650       
                                                                 
Total params: 27,882
Trainable params: 27,882
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
history=model.fit(train_X,train_y,validation_split=0.2,batch_size=64,epochs=20)

Epoch 1/20
750/750 [==============================] - 4s 5ms/step - loss: 0.5481 - accuracy: 0.8373 - val_loss: 0.2146 - val_accuracy: 0.9367
Epoch 2/20
750/750 [==============================] - 2s 3ms/step - loss: 0.2459 - accuracy: 0.9303 - val_loss: 0.1707 - val_accuracy: 0.9497
Epoch 3/20
750/750 [==============================] - 2s 3ms/step - loss: 0.1972 - accuracy: 0.9437 - val_loss: 0.1592 - val_accuracy: 0.9542
Epoch 4/20
750/750 [==============================] - 2s 3ms/step - loss: 0.1699 - accuracy: 0.9507 - val_loss: 0.1386 - val_accuracy: 0.9585
Epoch 5/20
750/750 [==============================] - 2s 3ms/step - loss: 0.1472 - accuracy: 0.9570 - val_loss: 0.1318 - val_accuracy: 0.9607
Epoch 6/20
750/750 [==============================] - 2s 3ms/step - loss: 0.1334 - accuracy: 0.9599 - val_loss: 0.1285 - val_accuracy: 0.9619
Epoch 7/20
750/750 [==============================] - 2s 3ms/step - loss: 0.1238 - accuracy: 0.9630 - val_loss: 0.1189 - val_accuracy: 0.9645
Epoch 